alter table public.ai_personalization_profiles drop constraint if exists ai_personalization_profiles_biggest_challenge_limit;
alter table public.ai_personalization_profiles add constraint ai_personalization_profiles_biggest_challenge_limit check (char_length(biggest_challenge) <= 120);
